# See https://www.chirpstack.io/network-server/install/config/ for a full
# configuration example and documentation.
#
# This file is for the CN470 band. See the examples/ folder for more
# configuration examples.

[postgresql]
dsn="postgres://chirpstack_ns:chirpstack_ns@postgresql/chirpstack_ns?sslmode=disable"

[redis]
url="redis://redis:6379"

[network_server]
net_id="000000"

[network_server.band]
name="CN470"

[network_server.network_settings]

  [[network_server.network_settings.extra_channels]]
  frequency=470300000
  min_dr=0
  max_dr=5

  [[network_server.network_settings.extra_channels]]
  frequency=470500000
  min_dr=0
  max_dr=5

  [[network_server.network_settings.extra_channels]]
  frequency=470700000
  min_dr=0
  max_dr=5

  [[network_server.network_settings.extra_channels]]
  frequency=470900000
  min_dr=0
  max_dr=5

  [[network_server.network_settings.extra_channels]]
  frequency=471100000
  min_dr=0
  max_dr=5

[network_server.gateway.backend.mqtt]
server="tcp://mosquitto:1883"

[join_server.default]
server="http://chirpstack-application-server:8003"
